### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by peng051410** [pouchdb/pouchdb-server#119] opened 2015-09-23 01:13 UTC
when i run sudo npm install -g pouchdb-server, i found a error under bellow:

ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/leveldown.node] Error 1
prebuild ERR! build `make` failed with exit code: 2
npm WARN optional dep failed, continuing leveldown@1.4.1

can you help me?thank you!

**Comment by nolanlawson** [comment] 2015-09-24 14:15
Sounds like a leveldown install error. What kind of operating system do you have?

**Comment by peng051410** [comment] 2016-01-20 14:09
Mac

**Comment by nolanlawson** [comment] 2016-01-24 21:45
Sorry, I'm going to close this since we can't really handle tech-support type issues in this repo... especially if the issue is leveldown.

Please confirm that `npm install leveldown` works on your machine, and if not, please provide them generous generous details about your OS version and everything.

**Closed by nolanlawson** 2016-01-24 21:45 UTC
