### ISSUE TITLE
continuous changes feed fails if there is an admin account

### ISSUE THREAD

**Issue by gr2m** [pouchdb/pouchdb-server#97] opened 2015-04-25 11:07 UTC
I tried to figure out why that is, but had no luck. Here's a test script to reproduce the issue: https://github.com/gr2m/pouchdb-server-continuous-feed-debug

Would appreciate some help with this <3

1. Install pouchdb-server: `npm install -g pouchdb-server`
2. Start pouchdb-server: `pouchdb-server -p 5985 --in-memory`
3. open http://localhost:5985/_utils
4. Create database "test"
5. Fix admin party, create admin user, username / password don't matter
6. Sign out
7. Open http://localhost:5985/test/_changes?since=0&feed=continuous&heartbeat=30000
8. Boom, you should see

```
TypeError: Object [object Promise] has no method 'on'
   at changes (/pouchdb-server-continuous-feed-debug/node_modules/pouchdb-server/node_modules/express-pouchdb/lib/routes/changes.js:43:35)
   at Layer.handle [as handle_request] (/pouchdb-server-continuous-feed-debug/node_modules/pouchdb-server/node_modules/express/lib/router/layer.js:82:5)
   at next (/pouchdb-server-continuous-feed-debug/node_modules/pouchdb-server/node_modules/express/lib/router/route.js:100:13)
   at Route.dispatch (/pouchdb-server-continuous-feed-debug/node_modules/pouchdb-server/node_modules/express/lib/router/route.js:81:3)
   at Layer.handle [as handle_request] (/pouchdb-server-continuous-feed-debug/node_modules/pouchdb-server/node_modules/express/lib/router/layer.js:82:5)
   at /pouchdb-server-continuous-feed-debug/node_modules/pouchdb-server/node_modules/express/lib/router/index.js:235:24
   at param (/pouchdb-server-continuous-feed-debug/node_modules/pouchdb-server/node_modules/express/lib/router/index.js:332:14)
   at param (/pouchdb-server-continuous-feed-debug/node_modules/pouchdb-server/node_modules/express/lib/router/index.js:348:14)
   at Function.proto.process_params (/pouchdb-server-continuous-feed-debug/node_modules/pouchdb-server/node_modules/express/lib/router/index.js:392:3)
   at /pouchdb-server-continuous-feed-debug/node_modules/pouchdb-server/node_modules/express/lib/router/index.js:229:12
   at Function.match_layer (/pouchdb-server-continuous-feed-debug/node_modules/pouchdb-server/node_modules/express/lib/router/index.js:296:3)
   at next (/pouchdb-server-continuous-feed-debug/node_modules/pouchdb-server/node_modules/express/lib/router/index.js:190:10)
   at /pouchdb-server-continuous-feed-debug/node_modules/pouchdb-server/node_modules/express/lib/router/index.js:192:16
   at Function.match_layer (/pouchdb-server-continuous-feed-debug/node_modules/pouchdb-server/node_modules/express/lib/router/index.js:296:3)
   at next (/pouchdb-server-continuous-feed-debug/node_modules/pouchdb-server/node_modules/express/lib/router/index.js:190:10)
   at /pouchdb-server-continuous-feed-debug/node_modules/pouchdb-server/node_modules/express/lib/router/index.js:192:16
```

**Comment by gr2m** [comment] 2015-04-25 11:10
btw the `--in-memory` doesn't matter, just makes testing simpler.

**Comment by gr2m** [comment] 2015-04-25 11:55
I think I found the cause of the issue. `pouchdb-security` is wrapping promises, so decorations like `.on` get lost. Here's the function in question (couldn't find the code on GitHub):

```js
function securityWrapper(checkAllowed, original, args) {
  var userCtx = args.options.userCtx || {
    //Admin party!
    name: null,
    roles: ["_admin"]
  };
  if (userCtx.roles.indexOf("_admin") !== -1) {
    return original();
  }
  if (!checkAllowed) {
    return Promise.resolve().then(throw401);
  }
  return filledInSecurity(args)
    .then(function (security) {
      if (!checkAllowed(userCtx, security)) {
        throw401();
      }
    })
    .then(original);
}
```

As there is no admin party anymore, the `userCtx.roles.indexOf` becomes `[]`. So the promise returned from `original` does not get returned, instead the one from `filledInSecurity(args)` does.

Changing the code to this below prevents exception:

```js
var promise = filledInSecurity(args)
    .then(function (security) {
      if (!checkAllowed(userCtx, security)) {
        throw401();
      }
    })
    .then(original);

  promise.on = function() {
    console.log('check 1,2')
    return promise;
  }

  return promise;
```

Instead, you'll see `check 1,2` in the logs :) 

I guess it'd be save to just add an `.on` method to all promises wrapped by `pouchdb-secruity`?

**Comment by gr2m** [comment] 2015-04-25 12:16
Here is a patch for `pouchdb-security` that fixes the problem:
https://gist.github.com/gr2m/e9d39d92f72a6e580dcd/revisions

Is `pouchdb-security` security somewhere on GitHub so I can submit a pull request? /cc @marten-de-vries

**Comment by nolanlawson** [comment] 2015-04-25 12:49
@gr2m I don't believe the fix is quite right. If the issue is that we are wrapping something that is supposed to be an `EventEmitter`, then shouldn't all events from the original object be forwarded to the new object? Or it should just extend `EventEmitter`. We've done this a few times, e.g. [here](https://github.com/pouchdb/pouchdb/blob/aef809491d3d19c878132c67ee2f62bf52f58e6a/lib/setup.js#L182-L185) and [here](https://github.com/pouchdb/pouchdb/blob/aef809491d3d19c878132c67ee2f62bf52f58e6a/lib/sync.js#L6-L8).

**Comment by marten-de-vries** [comment] 2015-04-25 12:51
@gr2m Duplicate of https://github.com/pouchdb/express-pouchdb/issues/202 . pouchdb-security's code is on Launchpad, not Github, because Python-PouchDB is and the tests are shared. I've been putting this off too long anyway, giving it a look now...

**Comment by gr2m** [comment] 2015-04-25 12:52
for the time being, this fork includes the fix, if anyone else runs into this before it gets resolved:
https://github.com/gr2m/pouchdb-server/

**Comment by nolanlawson** [comment] 2015-04-25 13:01
As far as I can see, the only events that are emitted on the `db` object itself are `'created'` and `'destroyed'` as well as the undocumented `'change'/'delete'/'update'/'create'` which I would like to remove (see https://github.com/pouchdb/pouchdb/pull/3740). It appears the second group isn't used anywhere in express-pouchdb or pouchdb, but the first group is indeed used by the changes listener.

So it looks like the fix is going to involve not only extended `EventEmitter`, but also making sure that the `'destroyed'` and `'created' events are called correctly. @marten-de-vries you can checkout [test.events.js](https://github.com/pouchdb/pouchdb/blob/aef809491d3d19c878132c67ee2f62bf52f58e6a/tests/integration/test.events.js) for how it should work. I admit it's a little bewildering, which is why I've been trying to trim it down to just two events.

Also note that these events should also be emitted by the `db.constructor`, whatever its constructor may be. Looks like in this case its constructor is just `Promise` (see[here](https://github.com/gr2m/pouchdb-security/blob/1afb969b32a8609c85ca3db93d50b912e766d7fb/index.js#L60-L87)), which is not going to work...

**Comment by gr2m** [comment] 2015-04-25 13:05
The issue here is about the `feed` object that `db.changes()` returns. `express-pouchdb` is using the `change`, `error` and `complete` events from it here: https://github.com/pouchdb/express-pouchdb/blob/master/lib/routes/changes.js

**Comment by nolanlawson** [comment] 2015-04-25 13:06
Sorry, confused. :confused: In that case there should be no issue, right? `db.changes()` returns a totally separate object, which yes, [is an event emitter](https://github.com/pouchdb/pouchdb/blob/aef809491d3d19c878132c67ee2f62bf52f58e6a/lib/changes.js#L12).

**Comment by nolanlawson** [comment] 2015-04-25 13:09
Oh, I see. Yeah, we are talking about the `Changes` object, not the `PouchDB` object. Gotcha.

**Comment by nolanlawson** [comment] 2015-04-25 13:12
In that case we are going to need `promise` to be an `EventEmitter` that forwards all events from `originalPromise`, similar to [what we did with sync() wrapping replicate()](https://github.com/pouchdb/pouchdb/blob/aef809491d3d19c878132c67ee2f62bf52f58e6a/lib/sync.js#L6-L8). I still think your fix @gr2m only solves the surface of the issue; it will never emit any change events to its listeners, which will probably mean that your continuous feed just never sends any updates.

**Comment by gr2m** [comment] 2015-04-25 13:15
Yeah I agree there must be better ways to fix it, but it works, I checked it.

**Comment by marten-de-vries** [comment] 2015-04-25 13:16
@gr2m's No, as far as I can see your solution is still incomplete:
- Even emitters have more methods than just .on()
- If anyone calls .on() *after* the promise resolved, it's going to be ignored.

**Comment by gr2m** [comment] 2015-04-25 13:20
Yeah, I just fixed `.on()`, what else is there? Once promise resolves, it gets set to what the `original()`s `.on()` method here: https://github.com/gr2m/pouchdb-security/blob/master/index.js#L74

**Comment by gr2m** [comment] 2015-04-25 13:22
I've extended my test script: https://github.com/gr2m/pouchdb-server-continuous-feed-debug/blob/master/index.js

Both docs that get created show up in the log, when my `pouchdb-server` fork is used

**Comment by marten-de-vries** [comment] 2015-04-25 13:25
@gr2m oh, right, I overlooked that. Other methods are documented here: https://nodejs.org/api/events.html#events_class_events_eventemitter . If your patch would include those, I guess it should work. I'm still trying the 'extend EventEmitter' way too, though, it might end up being less code to maintain in the long run.

**Comment by gr2m** [comment] 2015-04-25 13:27
I see my patch as a temporary workaround, it works fine because `.on()` is the only method that is used on `db.changes()`, the othrs EventEmitter methods are not as far as I know. I think this is good enough as a temporary fix, would be great to have `pouchdb-security` on GitHub, and then make a pull request for farther discussion. Looking forward to your proper fix for that. Thanks all :)

**Comment by nolanlawson** [comment] 2015-04-25 13:32
```js
for (method in require('events').EventEmitter.prototype) {
           promise[method] = originalPromise[method].bind(originalPromise);
}
```
This looks like it should work. It binds all of: `['setMaxListeners', 'emit', 'addListener', 'on', 'once', 'removeListener', 'removeAllListeners', 'listeners']`

**Comment by marten-de-vries** [comment] 2015-04-25 14:16
@nolanlawson That doesn't work because originalPromise is only going to be defined *after* an async security lookup in the database. At that time, the user already wants to have a promise with a ``.on()`` method. So I'm going to continue with the 'create a new wrapper EventEmitter' approach.

**Comment by gr2m** [comment] 2015-04-25 14:45
@nolanlawson what @marten-de-vries says. That's why I'm queuing the calls to `.on` until we have the promise from `original()`, see https://github.com/gr2m/pouchdb-security/blob/master/index.js#L81 and https://github.com/gr2m/pouchdb-security/blob/master/index.js#L70-L74

**Comment by marten-de-vries** [comment] 2015-04-25 16:33
I just published a new patch version of ``pouchdb-security``. It seems to have fixed the problem (tested with @gr2m's test setup. Very useful!). In the end I indeed used a new ``EventEmitter`` that is linked to the pouchdb one. I also abstracted that away into a new npm module, ``pouchdb-changeslike-wrapper``, to make reuse possible in ``pouchdb-security-db`` which needed a similar fix.

Code here: https://bazaar.launchpad.net/~marten-de-vries/python-pouchdb/0.x/view/head:/js/pouchdb-changeslike-wrapper/index.js

**Closed by marten-de-vries** 2015-04-25 16:33 UTC

**Comment by gr2m** [comment] 2015-04-25 17:03
confirmed, looks good, thanks @marten-de-vries

**Comment by nolanlawson** [comment] 2015-04-25 18:07
:dancer:

**Comment by denis-sokolov** [comment] 2015-04-27 08:44
Works for me! Thank you.
