### ISSUE TITLE
Getting an Error: could not locate the bindings file

### ISSUE THREAD

**Issue by megaed** [pouchdb/pouchdb-server#218] opened 2017-03-01 03:50 UTC
Tried to use pouchDB server but keep getting this error everytime I run the server and I can't connect to the database at all.

I'm not sure if this has something to do with me using NVM. This is running on a raspberry pi.
I also tried to install leveldown but still getting the same problem.

```
(node:30270) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): Error: Error: Could not locate the bindings file. Tried:
 → /home/pi/.nvm/versions/node/v7.5.0/lib/node_modules/pouchdb-server/node_modules/leveldown/build/leveldown.node
 → /home/pi/.nvm/versions/node/v7.5.0/lib/node_modules/pouchdb-server/node_modules/leveldown/build/Debug/leveldown.node
 → /home/pi/.nvm/versions/node/v7.5.0/lib/node_modules/pouchdb-server/node_modules/leveldown/build/Release/leveldown.node
 → /home/pi/.nvm/versions/node/v7.5.0/lib/node_modules/pouchdb-server/node_modules/leveldown/out/Debug/leveldown.node
 → /home/pi/.nvm/versions/node/v7.5.0/lib/node_modules/pouchdb-server/node_modules/leveldown/Debug/leveldown.node
 → /home/pi/.nvm/versions/node/v7.5.0/lib/node_modules/pouchdb-server/node_modules/leveldown/out/Release/leveldown.node
 → /home/pi/.nvm/versions/node/v7.5.0/lib/node_modules/pouchdb-server/node_modules/leveldown/Release/leveldown.node
 → /home/pi/.nvm/versions/node/v7.5.0/lib/node_modules/pouchdb-server/node_modules/leveldown/build/default/leveldown.node
 → /home/pi/.nvm/versions/node/v7.5.0/lib/node_modules/pouchdb-server/node_modules/leveldown/compiled/7.5.0/linux/arm/leveldown.node: unable to import leveldown
```

**Comment by gr2m** [comment] 2017-03-01 04:21
I think the problem is that leveldb was not compiled. Can you try to run `pouchdb-server --in-memory` and see if that works?

**Comment by megaed** [comment] 2017-03-01 05:53
How do I properly compile leveldb?

The pouchdb-server seems to work while running it in memory.

**Comment by gr2m** [comment] 2017-03-01 07:07
I don’t know about that. Maybe see if you can find help with the leveldb community? At least they claim the support Raspberry Pi in their README: https://github.com/Level/levelup

**Comment by megaed** [comment] 2017-03-01 07:28
Thanks for your quick response.

I have been able to get it to work by simply reinstalling node and deleting my node_modules folder then reinstalling pouchdb-server. It recompiled leveldb for me.

**Comment by garrensmith** [comment] 2017-03-01 12:02
Great. I'm going to close this issue.

**Closed by garrensmith** 2017-03-01 12:02 UTC
