### ISSUE TITLE
pouchdb without couchdb / replication

### ISSUE THREAD

**Issue by chrisschaub** [pouchdb/pouchdb-server#96] opened 2015-04-20 13:38 UTC
I have and express/mongodb app on the back-end. I was thinking about using pouchdb-server with the pouchdb-express to have my ios/android apps talk to the pouchdb-server so all instances of the mobile app can replicate data. So, the question is what datastore. I really don't want to run couchdb, hence the pouchdb-server. I really just need a datastore that works well with pouchdb-server and allow my pouchdb/ionic apps to all share data. Oh, and each user of the app has their own dedicated datastore. And all running the backend on AWS. Could I use pouchdb-server with leveldb/dynamo backend adaptor in a production environment? Any suggestions are appreciated.

**Comment by daleharvey** [comment] 2015-04-20 16:12
pouchdb-server by default has its own datastore included (leveldb)

**Comment by chrisschaub** [comment] 2015-04-20 16:20
Nice. I was thinking of use something like dynamo or mysql over AWS RDS so amazon handles backups and scaling. It seems there's a dynamo leveldown backend as well. I already have to maintain a mongodb, don't want to add another db if possible t really manage. Hoping to just use pouchdb-server and some managed backend for the datastorage. I'll have to check into leveldb as an option.

**Comment by daleharvey** [comment] 2015-04-20 16:23
Theres probably a few that will go to mongo - https://www.npmjs.com/package/mongodown etc, I havent used any so cant speak to their stability, and its probably worth noting you wont / shouldnt access the data directly via mongo, but it will keep it in the same place which can help ops

**Comment by nolanlawson** [comment] 2015-04-20 18:56
> works well with pouchdb-server and allow my pouchdb/ionic apps to all share data

So you do want replication. :wink: 

I still kinda like my [StackOverflow answer on this](http://stackoverflow.com/a/24392436/680742). Also [the FAQ answer](http://pouchdb.com/faq.html#sync_non_couchdb).

MongoDOWN/DynamoDOWN/etc. are neat, but you probably don't want them for a production server. They're pretty inefficient due to everything being through the key-value LevelUP API. And yeah, as Dale said, you can't actually use those databases directly; you still have to use the Pouch API.

If you want massive scaling, then you're in luck, because by design CouchDB/pouchdb-server can scale horizontally almost infinitely. Run out of capacity? Just spin up another instance and replicate to it. It's master-master, so you never have a single server being your bottleneck. Check the [replication guide](http://pouchdb.com/guides/replication.html) for more details on that. I think it's a pretty amazing feature. :smiley:

**Comment by chrisschaub** [comment] 2015-04-20 19:07
I'm actually leaning for a more simple datastore like aws dynamo or even
mysql. Amazon's RDS is really great for auto-scaling these types of things.
I would think dynamo db would be a great choice but have not tried the
leveldb adaptor.

On Mon, Apr 20, 2015 at 1:56 PM, Nolan Lawson <notifications@github.com>
wrote:

> works well with pouchdb-server and allow my pouchdb/ionic apps to all
> share data
>
> So you do want replication. [image: :wink:]
>
> I still kinda like my StackOverflow answer on this
> <http://stackoverflow.com/a/24392436/680742>. Also the FAQ answer
> <http://pouchdb.com/faq.html#sync_non_couchdb>.
>
> MongoDOWN/DynamoDOWN/etc. are neat, but you probably don't want them for a
> production server. They're pretty inefficient due to everything being
> through the key-value LevelUP API. And yeah, as Dale said, you can't
> actually use those databases directly; you still have to use the Pouch API.
>
> If you want massive scaling, then you're in luck, because by design
> CouchDB/pouchdb-server can scale horizontally almost infinitely. Run out of
> capacity? Just spin up another instance and replicate to it. It's
> master-master, so you never have a single server being your bottleneck.
> Check the replication guide <http://pouchdb.com/guides/replication.html>
> for more details on that. I think it's a pretty amazing feature. [image:
> :smiley:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pouchdb/pouchdb-server/issues/96#issuecomment-94539925>
> .
>



-- 
Christopher Schaub
http://chris.schaub.com

**Comment by Ravenstine** [comment] 2015-09-25 04:43
@nolanlawson I'm not sure I understand how MongoDB can be any less efficient as a Level backend than say Redis or SQLite.  Maybe I'm missing something...

**Comment by nolanlawson** [comment] 2015-09-25 11:56
@Ravenstine The LevelDOWN API assumes a basic key-value store, which is perfectly suited for LevelDB. But when you use such an API over MongoDB (i.e. MongoDOWN), it's not making the best use of Mongo's API because it's only using a tiny subset of it. It's basically ignoring the entire API and using the entire database as a simple Btree.

To be clear: anybody who wants to use a *DOWN database with pouchdb-server is absolutely welcome to, but I have not found one that gives any real benefit over the built-in LevelDOWN engine, except MemDOWN for obvious reasons.

**Comment by chrisschaub** [comment] 2015-09-25 13:45
And for Mongodb, there is this

https://atmospherejs.com/meteor/minimongo

We've been using Couch/Pouch with provision couch per user, works well.
Some issues with sync state, but mostly very solid. And then in ExpressJS,
you can mount Couchdb and get the data into Mongo via express. That way,
Couchdb and the Pouch clients are just there to keep the "truth" datastore
data, mongodb in our case,  replicating to clients. So Couch/Pouch are sort
of like a better version of AWS Cognito or a replicating datastore, but we
use Mongo/Express to hold the data for real and permanently.


On Fri, Sep 25, 2015 at 6:56 AM, Nolan Lawson <notifications@github.com>
wrote:

> @Ravenstine <https://github.com/Ravenstine> The LevelDOWN API assumes a
> basic key-value store, which is perfectly suited for LevelDB. But when you
> use such an API over MongoDB (i.e. MongoDOWN), it's not making the best use
> of Mongo's API because it's only using a tiny subset of it. It's basically
> ignoring the entire API and using the entire database as a simple Btree.
>
> To be clear: anybody who wants to use a *DOWN database with pouchdb-server
> is absolutely welcome to, but I have not found one that gives any real
> benefit over the built-in LevelDOWN engine, except MemDOWN for obvious
> reasons.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pouchdb/pouchdb-server/issues/96#issuecomment-143195220>
> .
>



-- 
Christopher Schaub
http://chris.schaub.com

**Comment by jingweno** [comment] 2016-10-19 15:42
:+1: to a postgresql or mysql backend. It can already sync using sqlite. Why wouldn't this work?

**Comment by nolanlawson** [comment] 2016-10-24 00:30
I'm going to close this; it is definitely not our roadmap. SQLite is an embedded database, hence makes perfect sense as an underlying backing store. Postgres and MySQL backend doesn't make sense for various reasons including https://pouchdb.com/faq.html#sync_non_couchdb and also the fact that it doesn't solve the problem people _really_ want to solve, which is that they want to use the SQL API to their favorite database and have PouchDB magically sync it, which is not possible due to CouchDB's revision semantics.

**Closed by nolanlawson** 2016-10-24 00:30 UTC
