### ISSUE TITLE
background replication

### ISSUE THREAD

**Issue by bortels** [pouchdb/pouchdb-server#102] opened 2015-06-12 17:48 UTC
My apologies if this is just me being ignorant - I still do not fully grok replication. 

So I have a set of 3 servers, any my goal is to replicate between them for redundancy and data sharing. I can manually replicate from 1 to another easily enough - and if I check "continuous", it will continuously replicate, unidirectionally, while I sit on that browser page. 

What I am trying to figure out is how to have this happen in the background, without a browser there to watch. I grepped for "live", and I think maybe this is simply not a feature pouchdb-server currently has? I think maybe couchdb does have this, and the lack here is maybe that you just let the couchdb server do that scheduling with the primary use-case for pouchdb being clients - but for pouchdb-server, it seems a gap. 

I tried adding a doc manually to _replicator - and it just sits (I assume replicating) until I give up. 

So - background replication between pouchdb-servers would be handy, or failing that something that talks about how it differs from couchdb (and possible workarounds). For now, I will simply (I hope) run a standalone node task that does a regular pouchdb connection and sync between my nodes, to act as an external replication service (hmm, and maybe backup).

**Comment by marten-de-vries** [comment] 2015-06-13 19:56
Replications should just work. They won't show up in Fauxton ('the GUI') because ``/_active_tasks`` isn't implemented, but they should run. If they don't (try it out by just creating a new doc and see if it replicates over), it's helpful if you could provide the http requests you are actually executing, or the steps you take inside Fauxton, so we can reproduce the problem.

Both CouchDB's 'continuous' and PouchDB's alias 'live' are supported, these options are passed straight on to PouchDB IIRC, which is probably why grepping for them didn't work.

**Comment by bortels** [comment] 2015-06-14 05:26
That's how I thought it should work, but it does not persist through a stop/start of the server, nor do I see a new entry in _replicator when I use the "Replication" sidebar in the gui. I was under the impression that continuous replication would be added to the _replicator database. (I do note I was wrong, in that if you navigate away, it does run in the background, at least until something bounces)

I use the GUI because my efforts to do it with curl fail (but only to _replicator):

 tbortels at Toms-iMac in ~ [22:20:32]
$ curl -X POST http://localhost:3333/test -d '{ "_id": "aaa", "source": "test", "target": "http://localhost:4444/test", "continuous": "true"}'
{"ok":true,"id":"ad6e2a46-65a1-4392-a795-a583a31b3933","rev":"1-d090284df0ea8b18d455319ec70ebb5e"}

# tbortels at Toms-iMac in ~ [22:21:51]
$ curl -X POST http://localhost:3333/_replicator -d '{ "_id": "aaadd", "source": "test", "target": "http://localhost:4444/test", "continuous": "true"}'
{"error":"forbidden","reason":"The `source' property must exist and be either a string or an object."}

(that last one surprised me a bit - I tried various combinations of PUT and POST both with and without the _id, same answer each time)

**Comment by marten-de-vries** [comment] 2015-06-14 13:55
Replications started using /_replicate (as opposed to /_replicator) don't persist over server restart. They don't in CouchDB either. The replication tab in Fauxton (the GUI) uses the first IIRC.

With the last command (post/put-ing to /_replicator) you're on the right way toward persisting replications. The command isn't exactly right though, you forget setting 'Content-Type: application/json' and the continuous field should be a boolean, not a string. E.g.:

marten@procyon:~/Bureaublad$ curl -X POST http://localhost:5984/_replicator -d '{ "_id": "aaadd", "source": "test", "target": "test2", "continuous": true}' -H 'Content-Type: application/json'

(I changed target and the port while testing locally).

**Comment by bortels** [comment] 2015-06-14 20:18
Hmm - so I am actually looking at a fauxton issue, I guess, at least in
part - it seems there should be a "persist thru restarts" checkbox to
determine the database, or whatever futon does/did - I do not have much
couchdb experience, so I defer to those more experienced. Or maybe better
docs, but that is also a couchdb thing...

Its a bit weird to me that the regular database takes a test/plain post -
but the replicator does not. I know you are aiming at duplicating what
couchdb does, so you may not have a lot of leeway there, but it might be
nice if either it was more forgiving on input (plaintext that parses to
json being maybe good enough?), or had a better error message - the one
about source was a tad misleading.

Thanks for the guidance - I think I have it from here. I am liking pouchdb
more than couchdb (the lightweight nature of things makes it much easier to
live with for dev!). Thank you to everyone involved.

On Sun, Jun 14, 2015 at 6:55 AM, Marten de Vries <notifications@github.com>
wrote:

> Replications started using /_replicate (as opposed to /_replicator) don't
> persist over server restart. They don't in CouchDB either. The replication
> tab in Fauxton (the GUI) uses the first IIRC.
>
> With the last command (post/put-ing to /_replicator) you're on the right
> way toward persisting replications. The command isn't exactly right though,
> you forget setting 'Content-Type: application/json' and the continuous
> field should be a boolean, not a string. E.g.:
>
> marten@procyon:~/Bureaublad$ curl -X POST
> http://localhost:5984/_replicator -d '{ "_id": "aaadd", "source": "test",
> "target": "test2", "continuous": true}' -H 'Content-Type: application/json'
>
> (I changed target and the port while testing locally).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pouchdb/pouchdb-server/issues/102#issuecomment-111828178>
> .
>



-- 
Tom Bortels -- bortels@gmail.com

"Believe nothing, no matter where you read it or who has said it,
  not even if I have said it,
   unless it agrees with your own reason and your own common sense."
    -- buddha

**Comment by marten-de-vries** [comment] 2015-06-15 09:08
The checkbox is probably missing because our Fauxton version hasn't been updated in a while. That's already tracked here: https://github.com/pouchdb/couchdb-fauxton/issues/7 .

As for the ``application/json`` thing, I agree that should have a clearer error message, pretty sure that CouchDB has one and it's just pouchdb-server being vague. I'm going to open a new issue for that.

**Comment by marten-de-vries** [comment] 2015-06-15 09:12
See #103 for the newly opened issue. Per
> Thanks for the guidance - I think I have it from here
I'm closing this issue. Feel free to reopen if you disagree or there's something else to discuss left.

**Closed by marten-de-vries** 2015-06-15 09:12 UTC
