### ISSUE TITLE
GET /_users/<currently signed-in user id> returns 404

### ISSUE THREAD

**Issue by gr2m** [pouchdb/pouchdb-server#101] opened 2015-05-14 15:16 UTC
Given that `GET /_session` returns

```json
{"ok":true,"userCtx":{"name":"test@example.com","roles":[]},"info":{"authentication_handlers":["cookie","default"],"authentication_db":"_users","authenticated":"cookie"}}
```

`GET /_users/org.couchdb.user%3Atest%40example.com` currently returns 

```json
{"error":"not_found","reason":"missing"}
```

But It should return the the user doc, as it belongs to the current signed-in user.

**Comment by marten-de-vries** [comment] 2015-05-14 19:54
Confirmed. It's a bug in ``pouchdb-system-db``/``pouchdb-auth``, this special case just wasn't added it seems.

**Comment by the-t-in-rtf** [comment] 2015-06-09 13:35
I am specifically testing a user management module and was hit hard by this.  Thankfully, in reviewing the code, I was able to come up with a workaround.

You can avoid the bug by adding the `_admin` role to a user's `role` property.

**Comment by gr2m** [comment] 2015-07-28 22:06
> Thanks for reporting. I can confirm this. It's a bug in pouchdb-system-db/pouchdb-auth, this special case just wasn't implemented it seems. couchdb-harness may be helpful here since it contains tests for behaviour like this.

@marten-de-vries any chance you could move pouchdb-system-db/pouchdb-auth to GitHub, so we can collaborate on it?

`couchdb-harness` looks amazing, great job! Can you give me guidance of what the steps would be to move on with it? I guess we have to add a test first for this issue here, see it fail, then fix pouchdb-server, then publish both?

**Comment by marten-de-vries** [comment] 2015-08-18 13:46
@gr2m Yes. (https://github.com/pouchdb/express-pouchdb/issues/232)

``couchdb-harness`` is couchdb's test suite, it's not really suitable to add new tests, but it does have a lot of existing tests that currently don't pass and could be enabled. There might be one for this bug inside.

An alternative would be to implement an express-pouchdb specific test (there are a few), or to just not implement a test but fix the issue. There's so much still untested currently that every improvement is welcome.

**Comment by gr2m** [comment] 2015-08-18 14:04
What would be your recommendation to move on? I'm happy to help, but need guidance to get started :)

**Comment by marten-de-vries** [comment] 2015-08-18 16:01
I just moved some of the directly relevant modules to Github. Fixing this would approximately go like this:

1) The problem is that protection of system databases (_replicator & _users) is currently too strong. That protection is defined here: https://github.com/pouchdb/pouchdb-system-db/blob/master/index.js#L84

A possible solution would be to just remove that statement, but that would leave ``.get()`` entirely unprotected. So:

2) We need to add some protection for this method at a higher level. In this case, in [pouchdb-replicator](https://github.com/pouchdb/pouchdb-replicator/blob/master/index.js) and [pouchdb-auth](https://github.com/pouchdb/pouchdb-auth/blob/master/index.js) which use it. The first can probably respond pretty closely to what the code did (although we should try out what CouchDB does here). The second needs a check. If the user is logged in && this is the user document, allow access. Else, return an error (again, see which error CouchDB uses).

I hope that helps a bit. These modules are underdocumented, but my first priority is moving them to Github now...

**Comment by gr2m** [comment] 2015-08-18 16:42
> I hope that helps a bit. These modules are underdocumented, but my first priority is moving them to Github now...

That's great, I'll try to give it a go! I'm pretty packed today & tomorrow, but hopefully have time for it on Thursday, thanks a lot! 

I also agree that moving them to GitHub is a great first step, it will allow all of us to help with improving the documentation / tests etc afterwards

**Comment by nolanlawson** [comment] 2015-08-19 03:19
closing as a dup of https://github.com/pouchdb/express-pouchdb/issues/240, also it's more appropriate for express-pouchdb

**Closed by nolanlawson** 2015-08-19 03:19 UTC
